### ISSUE TITLE
next new release with static binaries on Windows, MAC

### ISSUE THREAD

**Issue by eolivi** [openmeeg/openmeeg#163]
@agramfort said:
for me the next move is to make static binaries for the 3 platforms so we
can make a release. I would recommend to use mkl static libs for mac and
windows
and openblas for linux.

**Comment by eolivi** [comment]
how can we ship binaries with static MKL ? I thought the license of MKL prevent that ?
Although I have seen that you can download latest MKL for free but **for personal use only**
https://registrationcenter.intel.com/en/forms/?productid=2558&licensetype=2
.
I would have gone for a release with LAPACK on windows, and OpenBLAS on MAC (after checking which LAPACK is faster on MacOs vecLib or OpenBLAS)

**Comment by eolivi** [comment]
So, actually, it is ok because INRIA has bought the license to do so. 
Then, making the release is the next step ;-)

**Comment by agramfort** [comment]
@eolivi so summarize what's left to do:

- on http://openmeeg.gforge.inria.fr/download/?C=M;O=D both binaries work on my mac. We just need to decide what binaries we advertise (with vtk or not)

- why does the windows binaries have python? I would vote for not shipping binaries with python as it's not fully functional

- did someone test the linux binaries?

you're almost there. Call me if you need anything

**Comment by agramfort** [comment]
I am trying to help out here and for the first time I try to use the linux binaries on a linux system.

I logged onto the telecom cluster on which I have no admin rights to do:

```
wget http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk.tar.gz
tar xvfz OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk.tar.gz
```

first problem is that binaries are not executable so I need to do:

```
chmod +x bin/om_*
```

then I want to run om_assemble and I get:

```
gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk$ ./bin/om_assemble
./bin/om_assemble: error while loading shared libraries: libatlas.so.3: cannot open shared object file: No such file or directory
gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk$ ls lib
libOpenMEEGMaths.so  libOpenMEEGMaths.so.1  libOpenMEEGMaths.so.1.1.0  libOpenMEEG.so  libOpenMEEG.so.1  libOpenMEEG.so.1.1.0
```

is there hope to have working binaries on all three systems by the end of next week?

cc @mclerc @papadop

**Comment by papadop** [comment]
On 07/08/2017 03:37 PM, Alexandre Gramfort wrote:
> I am trying to help out here and for the first time I try to use the
> linux binaries on a linux system.
> 
> I logged onto the telecom cluster on which I have no admin rights to do:
> 
> |wget
> http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk.tar.gz
> tar xvfz OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk.tar.gz |
> 
> first problem is that binaries are not executable so I need to do:

That's totally strange... I did the same thing and all executable have
the proper permissions...

> 
> |chmod +x bin/om_* |
> 
> then I want to run om_assemble and I get:
> 
> |gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk$
> ./bin/om_assemble ./bin/om_assemble: error while loading shared
> libraries: libatlas.so.3: cannot open shared object file: No such file
> or directory

Strange again.. Why does the OPenBlas version require libatlas...
In my case it complains about libOpenMEEG.so which is indeed in lib.
When adding the lib directory, then it complains about other libraries
like libmatio.so.2 or various vtk libraries.

matio is available on my system but as limatio.so.4 and vtk libraries
seem to be installed but libraries are broken in multiple components
(i.e instead of libvtkCommon.so a lot of libvtkCommonXXX.so)...

I see no libatlas when using ldd....

This tar.gz distribution is really problematic...
IN the short term, it should be easy to have the proper libraries copied
in the tar.gz file (contrarily to what I said before to Emmanuel, but I
was not expecting/targetting the .tar.gz distribution but the rpm one).
Then remains the LD_LIBRARY_PATH trouble... Maybe the occasion to create
an om script (a la git) that does this magic and calls the proper om_XXX
utilities.

Je reste persuadé que rpm/deb est la meilleure maniere de distribuer
OpenMEEG (meme si le coup des librarairies qui different pose des
questions). A terme (mais ca n'est pas encore a l'ordre du jour car
c'est pas encore tres deployé), une approche a la docker ou flatpak est
peut-etre a considerer...

> gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-OpenMP-vtk$ ls lib
> libOpenMEEGMaths.so libOpenMEEGMaths.so.1 libOpenMEEGMaths.so.1.1.0
> libOpenMEEG.so libOpenMEEG.so.1 libOpenMEEG.so.1.1.0 |
> 
> is there hope to have working binaries on all three systems by the end
> of next week?

Je pense que copier les bonnes librairies dans le repertoire lib
d'openmeeg devrait etre super facile (puisque c'est deja le cas pour
windows et Mac). Uniquement pour faire une distrib a la tar.gz.

Le script aussi est simple a faire, par contre ca veut dire que les
bindings brainstorm et fieldtrop doivent etre adaptes (mais ils doivent
forcement l'etre ne serait ce que pour choisir le bon tar.gz, non ?).

	Theo.

**Comment by agramfort** [comment]
@eolivi can you do for linux the same thing you did for mac ie on travis in
the end remove all the dependencies and check that the produced binaries
work?

**Comment by eolivi** [comment]
this is not static, and it is called standalone.

I'll then do standalone packages. BUT

That is not the way to do it !  
rrrrrrrrrrrr..... we don't have to deliver  atlas, openblas, etc... people that come from brainstorm should be advised on how to get/install openmeeg.

**Comment by agramfort** [comment]
1+ for standalone

it's maybe not the way to do it but it's just how it works for all our users currently and how major packages in the field work. See FSL + FreeSurfer that i can install on any linux or mac without any admin rights.
