### ISSUE TITLE
HM matrix is different from the same head with rearranged .geom files

### ISSUE THREAD

**Issue by vhs304305** [openmeeg/openmeeg#486]
The geom file is quite convoluted to me. I tested the assemble_hm function with both the shipped example, head_model.geom and the slightly rearranged geom file. The assemble_hm produced different head matrix (same dimension but different number and file size).

The example, head_model.geom is,
////////////////////////////////////////////////
# Domain Description 1.0

Interfaces 3 Mesh

skull.tri
brain.tri
head.tri

Domains 4

Domain Scalp 1 -3
Domain Brain -2 shared
Domain Air 3
Domain Skull 2 -1
////////////////////////////////////////////////

The modified geom file is (using all the same meshes, with different order list),

////////////////////////////////////////////////
# Domain Description 1.0

Interfaces 3 Mesh

brain.tri
skull.tri
head.tri

Domains 4

Domain Brain -1
Domain Skull -2 1
Domain Scalp -3 2
Domain Air 3
////////////////////////////////////////////////

Everything else stays the same. The Assemble program produces different output .hm file.
Can anyone here explain what I did wrong?

**Comment by agramfort** [comment]
ping @papadop who designed this format.

**Comment by vhs304305** [comment]
@papadop and anyone developing OpenMEEG,
Whoever designed this geom format should be able to explain this simple question. Just use the above modified geom file instead of the shipped one, then run the assemble_head_matrix to see the different output.

**Comment by vhs304305** [comment]
Just run,

"om_assemble -HM head_model.geom head_model.cond output"

using modified head_model.geom to reproduce the problem.

**Comment by eolivi** [comment]
Using rearranged geom file creates different headmat:
So what ?

This may not be a problem. Since the indexing of the vertices changes, the HM (headmat) will also change. If you look at the publication, you'll see that the unkowns are the potential V_i (at each vertex of the mesh i) and the current p_i at each triangle of the mesh i. Usually the linear system to solve looks like:
```
HM * [V_1 V_2 V_3 p_1 p_2]^T = J
```

If you change the order of the meshes (e.g swap mesh_1 and mesh_2), the HM will be reordered so that:
```
HM * [V_2 V_1 V_3 p_2 p_1]^T = J
```

So having different HM for the same geometry should be ok. (you could still check the sub-blocks of HM are equal).

Are the EEG leadfield different in the end ? Can you do a comparison at sensor' position ? If the computed leadfields are different, then there is a bug.

**Comment by papadop** [comment]
Thank you for the report.

For some reason I still need to understand, I do no longer receives notifications for issues. So sorry for the delay in this answer. I will have a look at all the new issues later today or during the week-end and will answer as much as I can.

**Comment by papadop** [comment]
I think @eolivi  explained why you see differences. The order in which domains are declared in the geom file is used to order the elements of the matrices. As @eolivi explained you most probably just got the same matrices* but with permuted rows and columns. This should have no impact on the final leadfield....

* Small discrepancies in values may appear because of floating point rules but they should remain very low (below 10^{-5 or -6}).
