### ISSUE TITLE
Need to help to load sensor file

### ISSUE THREAD

**Issue by vhs304305** [openmeeg/openmeeg#518]
I  am having a strange issue and would like to get advice on how to solve the problem.

In the project, om_assemble, when the object
        Sensors electrodes("eeg_channels_locations.txt");
is created,
        Sensors(const char* filename): m_geo(NULL) { this->load(filename,'t'); } /*!< Construct from file. Option 't' is for text file.*/
is called.

But in my own dll project, when the object
        Sensors electrodes("eeg_channels_locations.txt");
is created,
        Geometry(const std::string& geomFileName, const bool OLD_ORDERING=false) {
            load(geomFileName, OLD_ORDERING);
        }
is called.

**Comment by papadop** [comment]
Two small things:
- Do you have some sample code to reproduce ?
- Which version of OpenMEEG are you using ? It looks like an old one as m_geo member has been renamed.

Both these informations would be needed to reproduce your problem. Otherwise, I do not have a clear idea of what happens. I do not see where the load method would construct a geometry....

**Comment by vhs304305** [comment]
My issue was caused by passing a std::string instead of const char* to the Sensor constructor. This issue should be closed.
