### ISSUE TITLE
fix Python API or example script

### ISSUE THREAD

**Issue by agramfort** [openmeeg/openmeeg#535]
when trying to run:

https://github.com/openmeeg/openmeeg_sample_data/blob/master/compute_leadfields.py

(which used to work 10 years ago when I wrote it :) ) 

it now crashes. I think the Python API has changed.

@papadop can you have a look? Maybe just update the demo script in this data repo?

🙏

**Comment by papadop** [comment]
Yes I will have a look.
The python API may have changed to follow the C++ one. Normally improved....
The thing is 10 years ago, we had huge memory leaks, so python was crashing very easily. I think, we are a little bit better now, but we may have introduced some changes, even if I thought we were mostly python backward compatible.

**Comment by papadop** [comment]
OK, it seems that I adapted the file to the new API (which is surprising, I do not remember that).
But there is one error with the line:
dsm = om.DipSourceMat(geom, dipoles, "Brain")
I think that what happened is the following. In the API change, I made "raised" the integrator parameter to the high level functions, so that it is now explicitly possible to change its parameters (not yet in the om_xxx binaries, but that is now a possibility). This integrator is added as an optional parameter.
DipSourceMat already had one such optional parameter (for a domain) and for some reasons, I thought we would like to change the integrator more often than the domain, so I put the integrator first, This is the cause of the problem.
When I tested it, I probably forgot to remove "tmp/dsm.mat", so the line was probably not tested.

There are multiple ways (at least 3) to correct the problem.

The first one is just to suppress the "Brain" in the above call. It means that DipSourceMat will get an empty string for the domain, and then will take the conductivity of the domain to which the dipole belongs to. I must say, that it is not clear why we would allow enforcing a given conductivity (this is the role of the "Brain" parameter) ??? Probably, for handling small errors in dipole locations which may place them in a neighboring domain (i.e. CSF), but I'm unsure that enforcing the conductivity this way is safe.

For the record:
```
>>> dsm = om.DipSourceMat(geom, dipoles)
Interface::contains_point(193.74 108.697 87.564) Error. Are you sure the interface "Cortex" is closed? Solid angle: 1.19878e-15*PI.
Interface::contains_point(193.74 108.697 87.564) Error. Are you sure the interface "Cortex" is closed? Solid angle: 1.19878e-15*PI.
Interface::contains_point(177.959 112.361 48.9218) Error. Are you sure the interface "Cortex" is closed? Solid angle: 6.72831e-16*PI.
Interface::contains_point(177.959 112.361 48.9218) Error. Are you sure the interface "Cortex" is closed? Solid angle: 6.72831e-16*PI.
Interface::contains_point(179.186 106.772 50.7651) Error. Are you sure the interface "Cortex" is closed? Solid angle: 1.95195e-16*PI.
Interface::contains_point(179.186 106.772 50.7651) Error. Are you sure the interface "Cortex" is closed? Solid angle: 1.95195e-16*PI.
Interface::contains_point(179.311 103.081 53.001) Error. Are you sure the interface "Cortex" is closed? Solid angle: 4.05438e-15*PI.
Interface::contains_point(179.311 103.081 53.001) Error. Are you sure the interface "Cortex" is closed? Solid angle: 4.05438e-15*PI.
```

Another possibility, with maximum backward compatibility, is to add a function:
```
Matrix
DipSourceMat(const Geometry& geo,const Matrix& dipoles,const std::string& domain_name) {
        return DipSourceMat(geo,dipoles,Integrator(3,10,0.001),domain_name);
}
```
which should cover the om.DipSourceMat(geom, dipoles, "Brain") case....

Finally, I can exchange the order of the two optional parameters in DipSourceMat....

**Comment by agramfort** [comment]
Honestly I don’t have a strong opinion of how to fix. But I would just aim to advertise and document something that works. 🙏

**Comment by papadop** [comment]
Done with PR #537.
