### ISSUE TITLE
intercept malloc errors

### ISSUE THREAD

**Issue by agramfort** [openmeeg/openmeeg#65]
to make the program crash smoothly....

cc @papadop @mclerc

**Comment by papadop** [comment]
Well, there is a not too difficult way in linux, but on windows or Mac, that's much more convoluted.
The problem is to know what is the extent of these interceptions. If its only on OpenMEEG, that's easy, we just need to add the proper try/catch if they are missing.
The problems arise with matio, hdf5, zlib and lapack which we do not control. There we have to play with linker tricks to intercept all malloc references and that is painful and error prone:
http://wwwold.cs.umd.edu/Library/TRs/CS-TR-4585/CS-TR-4585.pdf

**Comment by agramfort** [comment]
the idea would to display a meaningful message saying that matrix could not be allocated and that XX MB of memory is needed to work these data.

**Comment by agramfort** [comment]
see for example:

http://neuroimage.usc.edu/forums/archive/index.php/t-1138.html?s=8f45f39bc0ff2aa42fd284400c8f7184

**Comment by agramfort** [comment]
http://neuroimage.usc.edu/forums/showthread.php?1138

**Comment by papadop** [comment]
For matio, there is a way to deal with the problem.... All errors are sent to a function which is tunable. In that function, we can turn matio critical messages into exceptions. I have a prototype patch. I need to find a way to test it. If hdf5, zlib and matio do their job cleanly (i.e. zlib & hdf5 send an error which is captured by matio), then this is a solution. lapack never uses malloc, so we are safe there but atlas & consort do..... Not finished but hopefully, we improved things....

**Comment by agramfort** [comment]
can you do this without patching matio? so we can still use their release version?

**Comment by papadop** [comment]
Yep, it is stock matio. Even though I had to make some ugly stuff (duplicate some matio code) to get access to some log level constants which are not exported currently. I could avoid that but the openmeeg code would be weaker and more prone to changes in matio. I will submit a patch to matio to aim at improving that in the future.

**Comment by agramfort** [comment]
gr8

**Comment by papadop** [comment]
PR #110
