### ISSUE TITLE
openmeeg tests fail on Debian build 

### ISSUE THREAD

**Issue by juricast** [openmeeg/openmeeg#75]
Hello,

Package openmeeg fail to build from source on Debian.
https://buildd.debian.org/status/package.php?p=openmeeg&suite=sid

Could you please take a look?

Any suggestions are welcomed.

Regards,
Jurica

**Comment by papadop** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 06/22/2015 05:43 PM, juricast wrote:
> Hello,
> 
> Package openmeeg fail to build from source on Debian. 
> https://buildd.debian.org/status/package.php?p=openmeeg&suite=sid
> 
> Could you please take a look?
> 
> Any suggestions are welcomed.

I'm looking at it right now...I'll let you know as soon as I find what
happened. And will commit a fix.

	Theo.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlWIMKkACgkQEr8WrU8nPV13VQCfbxgQkNGZdu3C1CQtEe3Y3D1K
aKgAoJNtqDInnMiiHOJ6tkC9visPCcHx
=KRiW
-----END PGP SIGNATURE-----

**Comment by papadop** [comment]
OK. I believe I know the problem. I now forced the use of matio to output the files in matlab format. We furthermore prefer the use of the format matlab 7.3 as it provides in file compression and is really helpful for users with very big matrices (which arises quite often). I strongly suspect that the version of matio you use is not compiled with matlab 7.3 file format support and that is why you get the errors.

So basically its a combination of us imposing matio use and you not supporting matlab 7.3 file format in matio,

What I do not understand is that it seems that you have the matio requirement, so I'm not sure to understand why the saving/loading tests were not done before: 

#ifdef USE_MATIO
    std::cout << "MAT :" << std::endl;
    v.save("tmp_matrix.mat");
    v.load("tmp_matrix.mat");
    v.info();
#endif

Probably a bug on our side which was deciding that we could not use your version of matio.

I certainly can fix the build system to check that matlab 7.3 support is provided and I will do that (later tonight). But on the other end, this will somewhat cripple OpenMEEG so that I urge you to try to add this support in matio if you can...

**Comment by papadop** [comment]
With a proper matio (and when some other problems I need to correct do not exist), everything seems to compiles fine for ubuntu (which should be similar to debian). See
https://ci.inria.fr/openmeeg/job/OpenMEEG-linux/

**Comment by juricast** [comment]
Please take a look at:
https://buildd.debian.org/status/logs.php?pkg=openmeeg

version 2.0.0.dfsg-5.1 was built almost on every architecture successfully.
Difference between version 2.0.0.dfsg-5.1 and 2.0.0.dfsg-5.2:
http://metadata.ftp-master.debian.org/changelogs/main/o/openmeeg/openmeeg_2.0.0.dfsg-5.2_changelog

Thank you!

Regards,
Jurica

**Comment by papadop** [comment]
Well it seems things have changed... Things seem to mostly work now. Except for S390 and PPC64, And to some extend Hurd (but in this case all test pass, so this seems more a packaging problem as .so files seems to not be found). For S290 and PPC64, it is difficult to analyze without a machine at hand....

**Comment by agramfort** [comment]
we'll update the debian package after the release of 2.4
